from tkinter import *
import calendar
screen=Tk()
screen.title("calendar")
screen.geometry("300x300")
calendar=Label(screen,text="Calendar",bg="blue",fg="yellow",font=("Arial",40,"bold"))
calendar.place(x=35,y=0)
year=Label(screen,text="Enter Year",bg="white",fg="red")
year.place(x=115,y=70)
entrybox=Entry(screen)
entrybox.place(x=80,y=100)
exit1=Button(screen,text="Exit",bg="yellow",fg="black",command=exit)
exit1.place(x=120,y=170)
def displaycal():
    screen1=Tk()
    screen1.geometry("550x600")
    fetch=int(entrybox.get())
    content=calendar.calendar(fetch)
    cal_year=Label(screen1,text=content)
    cal_year.place(x=0,y=0)
    mainloop()
show=Button(screen,text="Show Calendar",bg="black",fg="white",command=displaycal)
show.place(x=120,y=140)
mainloop()